## **Importing Numpy**

In [1]:
import numpy as np


## **Creating a Numpy Array**

In [4]:
# Create a NumPy array of random float numbers
np_array = np.random.rand(10)
np_array

array([0.74741127, 0.89605614, 0.23094932, 0.06507348, 0.6700732 ,
       0.38464402, 0.16176724, 0.55536433, 0.29473703, 0.93370799])

## **Arithematic Operations on Single Array**

In [5]:
addition=np_array+485                        #it will add 485 in each element in the array
multiplication=np_array*485                  #it will multiply each element in the array with 485
dvision=np_array/1                           #it will divide each element in the array with 1
substraction=np_array-1                      #it will substract each element in the array with 1
modulus=np_array%10                          #it will take mudulus of each element in the array with 10

In [6]:
addition

array([485.74741127, 485.89605614, 485.23094932, 485.06507348,
       485.6700732 , 485.38464402, 485.16176724, 485.55536433,
       485.29473703, 485.93370799])

In [7]:
multiplication

array([362.49446748, 434.58722789, 112.01041908,  31.56064004,
       324.98550427, 186.55234837,  78.45711114, 269.35170176,
       142.94745714, 452.84837389])

In [8]:
dvision

array([0.74741127, 0.89605614, 0.23094932, 0.06507348, 0.6700732 ,
       0.38464402, 0.16176724, 0.55536433, 0.29473703, 0.93370799])

In [9]:
substraction

array([-0.25258873, -0.10394386, -0.76905068, -0.93492652, -0.3299268 ,
       -0.61535598, -0.83823276, -0.44463567, -0.70526297, -0.06629201])

In [10]:
modulus

array([0.74741127, 0.89605614, 0.23094932, 0.06507348, 0.6700732 ,
       0.38464402, 0.16176724, 0.55536433, 0.29473703, 0.93370799])

## **Measures of Centre**

In [11]:
# Calculate the mean and standard deviation of the array
mean_value = np.mean(np_array)
std_deviation = np.std(np_array)

print("Mean:", mean_value)
print("Standard Deviation:", std_deviation)


Mean: 0.4939784022786348
Standard Deviation: 0.29482088898086944
